
(()=>{
"use strict";
const $h=id=>document.getElementById(id);
const T=[
{k:["despesa","gasto","conta a pagar"],t:"Lançar uma despesa",s:["Abra Financeiro.","Toque em Nova despesa / conta.","Informe data, valor, categoria, pessoa/empresa e talhão quando aplicável.","Se ainda não pagou, deixe Pendente e informe o vencimento.","Revise e salve."],tip:"Use Duplicar quando quiser reaproveitar um lançamento antigo.",a:[["Nova despesa","despesa"],["Ir ao Financeiro","financeiro"]]},
{k:["receita","entrada","recebi"],t:"Lançar uma receita",s:["Abra Financeiro.","Toque em Nova receita.","Informe origem, valor e data.","Marque Recebido ou Pendente.","Salve."],tip:"Vendas de café podem gerar a receita automaticamente.",a:[["Nova receita","receita"],["Ir ao Financeiro","financeiro"]]},
{k:["parcial","pagar parte","receber parte"],t:"Pagamento ou recebimento parcial",s:["Abra Financeiro e localize a conta.","Toque no botão de baixa.","Informe o valor pago ou recebido agora.","Escolha conta/caixa e data.","O restante continua em aberto."],tip:"O status só fica totalmente quitado quando o saldo chega a zero.",a:[["Ir ao Financeiro","financeiro"]]},
{k:["latao","latoes","colhedor","apanha"],t:"Registrar latões",s:["Abra Colheita.","Entre em Colhedores / Latões.","Crie uma nova apanha.","Escolha colhedor, talhão, quantidade e valor por latão.","Salve."],tip:"O custo do colhedor fica integrado ao Financeiro.",a:[["Ir à Colheita","producao"]]},
{k:["secador","lote","secagem"],t:"Controlar o secador",s:["Registre primeiro os latões.","Na Colheita, abra Secador.","Crie o lote e informe os latões enviados.","Quando terminar, feche o lote informando as sacas produzidas.","O estoque é atualizado."],tip:"Lotes com mais de um talhão são distribuídos proporcionalmente.",a:[["Ir à Colheita","producao"]]},
{k:["manejo","adubacao","pulverizacao","fertirrigacao","irrigacao","poda"],t:"Registrar manejo",s:["Abra Colheita e localize Manejo da lavoura.","Toque em Novo manejo.","Escolha data, talhão, safra e tipo.","Adicione insumos quando houver.","Ao concluir, o app baixa o estoque e calcula o custo aplicado."],tip:"Se ainda será realizado, deixe como Programado.",a:[["Ir à Colheita","producao"]]},
{k:["insumo","estoque","adubo estoque","defensivo"],t:"Controlar estoque de insumos",s:["Abra Perfil.","Entre em Estoque de insumos.","Cadastre o produto e a unidade.","Use Movimentar para entradas e saídas.","Acompanhe saldo, custo médio e estoque mínimo."],tip:"As saídas podem ser vinculadas ao talhão.",a:[["Abrir insumos","insumos"],["Ir ao Perfil","perfil"]]},
{k:["solo","analise de solo","ph","v%"],t:"Análise de solo",s:["Abra Perfil.","Entre em Análises de solo.","Escolha talhão, data e profundidade.","Digite os valores do laudo.","Salve para formar o histórico."],tip:"Na ficha do talhão você pode comparar análises.",a:[["Ir ao Perfil","perfil"]]},
{k:["safra","fechar safra","resultado da safra"],t:"Gestão da safra",s:["Abra Perfil e Gestão da safra.","Escolha a safra.","Revise produção, estoque, receitas, despesas e custo por saca.","Confira o desempenho por talhão.","Faça o fechamento depois da conferência."],tip:"O fechamento não apaga contas pendentes.",a:[["Ir ao Perfil","perfil"]]},
{k:["relatorio","pdf","caixa realizado"],t:"Relatórios",s:["Abra Relatórios.","Escolha período, safra e filtros.","Use Competência ou Caixa realizado.","Gere PDF ou CSV quando necessário."],tip:"Caixa realizado mostra o dinheiro efetivamente movimentado.",a:[["Abrir Relatórios","relatorios"]]},
{k:["backup","restaurar"],t:"Backup",s:["Abra Perfil.","Localize Dados e backup.","Baixe o arquivo.","Guarde-o em local seguro.","Use Importar se precisar restaurar."],tip:"O backup é uma segurança adicional ao Firebase.",a:[["Ir ao Perfil","perfil"]]}
];
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
function find(q){const n=norm(q);let best=null,score=0;for(const t of T){let s=0;for(const k of t.k)if(n.includes(norm(k)))s+=norm(k).split(/\s+/).length+1;if(s>score){score=s;best=t}}return best}
function render(t){if(!t)return generic();$h("aiResumoV123").textContent=t.t;$h("helpRespostaV123").innerHTML="<ol>"+t.s.map(x=>`<li>${x}</li>`).join("")+"</ol>"+(t.tip?`<div class="tip"><strong>Dica:</strong> ${t.tip}</div>`:"");$h("aiAcoesV123").innerHTML=(t.a||[]).map(([l,a],i)=>`<button type="button" class="${i?"secondary":""}" onclick="executarAjudaAcaoV123('${a}')">${l}</button>`).join("");$h("aiResultadoV123").classList.remove("hidden")}
function generic(){$h("aiResumoV123").textContent="Posso orientar sobre o aplicativo";$h("helpRespostaV123").innerHTML="<p>Pergunte sobre despesas, pagamentos, latões, secador, manejo, insumos, solo, safra, relatórios ou backup.</p>";$h("aiAcoesV123").innerHTML="";$h("aiResultadoV123").classList.remove("hidden")}
window.abrirAssistenteIA=function(){if($h("aiTextoV123"))$h("aiTextoV123").value="";$h("aiResultadoV123")?.classList.add("hidden");if($h("helpContextoV123")){const n=document.querySelector(".navbtn.active")?.dataset?.nav||"resumo";$h("helpContextoV123").textContent=({resumo:"Início",financeiro:"Financeiro",producao:"Colheita",relatorios:"Relatórios",perfil:"Perfil"})[n]||"Início"}abrirModal("modalAssistenteV123")};
window.aiAnalisarV123=function(){const q=$h("aiTextoV123")?.value.trim();if(!q){toast("Digite sua dúvida.");return}render(find(q))};
window.perguntarAjudaV123=function(q){$h("aiTextoV123").value=q;render(find(q))};
window.ajudaTelaAtualV123=function(){const n=document.querySelector(".navbtn.active")?.dataset?.nav||"resumo";render(find(({resumo:"safra",financeiro:"despesa parcial",producao:"latoes manejo",relatorios:"relatorio",perfil:"insumo solo backup"})[n]))};
window.executarAjudaAcaoV123=function(a){fecharModal("modalAssistenteV123");const nav=n=>{const b=document.querySelector(`[data-nav="${n}"]`);trocarAba(n,b)};if(a==="financeiro")nav("financeiro");else if(a==="producao")nav("producao");else if(a==="relatorios")nav("relatorios");else if(a==="perfil")nav("perfil");else if(a==="despesa"){nav("financeiro");setTimeout(()=>abrirLancamento("despesa"),60)}else if(a==="receita"){nav("financeiro");setTimeout(()=>abrirLancamento("receita"),60)}else if(a==="insumos")setTimeout(()=>abrirEstoqueInsumosV126(),40)};
document.addEventListener("DOMContentLoaded",()=>{$h("aiTextoV123")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();aiAnalisarV123()}})});
})();
