(()=>{
"use strict";
const COLLECTIONS_V127=["lancamentos","talhoes","colheitas","vendas","trabalhadores","apanhas","lotes","safras","pessoas","analisesSolo","baixasFinanceiras","contasFinanceiras","recorrenciasFinanceiras","orcamentosSafra","fechamentosSafra","insumos","movimentacoesInsumos","lixeiraV126","historicoV126","manejos"];
const META_KEYS=new Set(["criadoEm","alteradoEm","alteradoPor","syncVersion"]);
const deviceId=(()=>{let x=localStorage.getItem("financeiro_device_v127");if(!x){x=(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36));localStorage.setItem("financeiro_device_v127",x)}return x})();
window.__syncRevV127=Number(window.__syncRevV127||0);window.__pendenciasSyncV127=Number(window.__pendenciasSyncV127||0);

function estrutura(){garantirEstruturaV126();if(!Array.isArray(estado.manejos))estado.manejos=[];if(!estado.syncDeletedV127||typeof estado.syncDeletedV127!=="object")estado.syncDeletedV127={};if(!estado.syncInfoV127||typeof estado.syncInfoV127!=="object")estado.syncInfoV127={};}
function semMeta(o){if(!o||typeof o!=="object")return o;const x={};Object.keys(o).sort().forEach(k=>{if(!META_KEYS.has(k))x[k]=o[k]});return x}
function igual(a,b){try{return JSON.stringify(semMeta(a))===JSON.stringify(semMeta(b))}catch{return false}}
function recTs(x){const v=x?.alteradoEm||x?.atualizadoEm||x?.criadoEm||"";const t=Date.parse(v);return Number.isFinite(t)?t:0}
function markChanges(){estrutura();const old=window.__snapshotV127||{};let changed=0;const now=new Date().toISOString();for(const c of COLLECTIONS_V127){const cur=Array.isArray(estado[c])?estado[c]:[],prev=Array.isArray(old[c])?old[c]:[],pm=new Map(prev.filter(x=>x?.id).map(x=>[x.id,x]));const cm=new Map(cur.filter(x=>x?.id).map(x=>[x.id,x]));for(const x of cur){if(!x?.id)continue;const p=pm.get(x.id);if(!p){x.criadoEm=x.criadoEm||now;x.alteradoEm=now;x.alteradoPor=deviceId;x.syncVersion=Number(x.syncVersion||0)+1;changed++}else if(!igual(x,p)){x.criadoEm=x.criadoEm||p.criadoEm||now;x.alteradoEm=now;x.alteradoPor=deviceId;x.syncVersion=Math.max(Number(x.syncVersion||0),Number(p.syncVersion||0))+1;changed++}}for(const p of prev){if(p?.id&&!cm.has(p.id)){estado.syncDeletedV127[`${c}:${p.id}`]=Date.now();changed++}}}estado.syncInfoV127={deviceId,localUpdatedAt:Date.now()};window.__snapshotV127=structuredClone(estado);if(changed){window.__syncRevV127++;window.__pendenciasSyncV127+=changed;if(usuarioAtual?.uid)localStorage.setItem(`financeiro_sync_pending_v127_${usuarioAtual.uid}`,"1")}return changed}

window.mergeStateV127=function(remote={},local={}){const out={...remote,...local};const del={...(remote.syncDeletedV127||{}),...(local.syncDeletedV127||{})};for(const [k,v] of Object.entries(remote.syncDeletedV127||{}))del[k]=Math.max(Number(del[k]||0),Number(v||0));for(const [k,v] of Object.entries(local.syncDeletedV127||{}))del[k]=Math.max(Number(del[k]||0),Number(v||0));out.syncDeletedV127=del;for(const c of COLLECTIONS_V127){const rm=new Map((Array.isArray(remote[c])?remote[c]:[]).filter(x=>x?.id).map(x=>[x.id,x])),lm=new Map((Array.isArray(local[c])?local[c]:[]).filter(x=>x?.id).map(x=>[x.id,x]));const ids=new Set([...rm.keys(),...lm.keys()]),arr=[];for(const id of ids){const r=rm.get(id),l=lm.get(id),tomb=Number(del[`${c}:${id}`]||0);let chosen;if(!r)chosen=l;else if(!l)chosen=r;else{const rv=Number(r.syncVersion||0),lv=Number(l.syncVersion||0);if(lv!==rv)chosen=lv>rv?l:r;else chosen=recTs(l)>=recTs(r)?l:r}if(chosen&&tomb<recTs(chosen))arr.push(chosen);else if(chosen&&tomb===0)arr.push(chosen)}out[c]=arr}out.syncInfoV127={...(remote.syncInfoV127||{}),...(local.syncInfoV127||{}),mergedAt:Date.now()};return out};

window.appBridge.getLocalEstadoV127=function(uid){try{return JSON.parse(localStorage.getItem("financeiro_sitio_"+uid)||"null")}catch{return null}};

const basePersist=window.persistir;
window.persistir=function(){markChanges();salvarLocal();renderTudo();if(!suspendSync&&window.cloudSync)window.cloudSync.agendar()};

/* manejo */
function insumo(id){return estado.insumos.find(x=>x.id===id)}
function manejoMovs(id){return estado.movimentacoesInsumos.filter(m=>m.manejoId===id)}
function custoManejo(m){return Number(m?.custoInsumos||0)}
function custoTalhao(talhaoId,safraId="todos"){return estado.manejos.filter(m=>m.status==="concluido"&&m.talhaoId===talhaoId&&(safraId==="todos"||m.safraId===safraId)).reduce((s,m)=>s+custoManejo(m),0)}
window.custoManejoTalhaoV127=custoTalhao;
function manejoOverdue(m){return m.status==="programado"&&m.data&&m.data<hoje()}
function produtosHTML(prod=[]){return prod.map(p=>{const i=insumo(p.insumoId);return `<span class="v127-product-chip">${esc(i?.nome||"Produto")} • ${num(p.quantidade)} ${esc(i?.unidade||"")}</span>`}).join("")}
function fillManejoSelects(){const t=$("manejoTalhaoV127"),s=$("manejoSafraV127");if(t)t.innerHTML=`<option value="">Selecione...</option>`+estado.talhoes.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join("");if(s)preencherSelectSafrasV124(s,false,estado.safraAtivaId);}
function produtoRow(p={}){const opts=`<option value="">Selecione o insumo</option>`+estado.insumos.map(i=>`<option value="${i.id}" ${i.id===p.insumoId?"selected":""}>${esc(i.nome)} • saldo ${num(saldoInsumoV126(i.id))} ${esc(i.unidade||"")}</option>`).join("");return `<div class="v127-product-row"><div class="field"><label>Produto</label><select class="manej-prod-id" onchange="previewManejoV127()">${opts}</select></div><div class="field"><label>Qtd.</label><input class="manej-prod-qtd" type="number" step="0.01" min="0" value="${p.quantidade||""}" oninput="previewManejoV127()"></div><button class="v127-remove-product" type="button" onclick="this.closest('.v127-product-row').remove();previewManejoV127()">×</button></div>`}
window.adicionarProdutoManejoV127=function(p={}){$("manejoProdutosV127").insertAdjacentHTML("beforeend",produtoRow(p));previewManejoV127()};
function lerProdutos(){return [...document.querySelectorAll("#manejoProdutosV127 .v127-product-row")].map(r=>({insumoId:r.querySelector(".manej-prod-id")?.value||"",quantidade:Number(r.querySelector(".manej-prod-qtd")?.value||0)})).filter(p=>p.insumoId&&p.quantidade>0)}
window.previewManejoV127=function(){if(!$("manejoCustoPreviewV127"))return;const ps=lerProdutos();let total=0;const det=[];for(const p of ps){const i=insumo(p.insumoId),cm=custoMedioInsumoV126(p.insumoId);total+=p.quantidade*cm;det.push(`${i?.nome||"Produto"}: ${num(p.quantidade)} ${i?.unidade||""} × ${moeda(cm)}`)}$("manejoCustoPreviewV127").innerHTML=ps.length?`Custo estimado dos insumos: <strong>${moeda(total)}</strong>${det.length?`<br><small>${esc(det.join(" • "))}</small>`:""}`:"Nenhum insumo selecionado. Manejos como irrigação ou poda podem ser registrados sem produto."};
window.abrirManejoV127=function(id=""){estrutura();fillManejoSelects();const m=id?estado.manejos.find(x=>x.id===id):null;$("manejoIdV127").value=m?.id||"";$("tituloManejoV127").textContent=m?"Editar manejo":"Novo manejo";$("manejoDataV127").value=m?.data||hoje();$("manejoStatusV127").value=m?.status||"programado";$("manejoTalhaoV127").value=m?.talhaoId||"";$("manejoSafraV127").value=m?.safraId||estado.safraAtivaId||"";$("manejoTipoV127").value=m?.tipo||"Adubação";$("manejoResponsavelV127").value=m?.responsavel||"";$("manejoObsV127").value=m?.obs||"";$("manejoProdutosV127").innerHTML="";(m?.produtos||[]).forEach(p=>adicionarProdutoManejoV127(p));previewManejoV127();abrirModal("modalManejoV127")};
function validateStock(prod,oldManejoId=""){const oldQty={};if(oldManejoId)for(const m of manejoMovs(oldManejoId)){oldQty[m.insumoId]=(oldQty[m.insumoId]||0)+Number(m.quantidade||0)}for(const p of prod){const i=insumo(p.insumoId);const avail=saldoInsumoV126(p.insumoId)+(oldQty[p.insumoId]||0);if(p.quantidade>avail+0.0001)return `${i?.nome||"Produto"}: precisa ${num(p.quantidade)} ${i?.unidade||""}, disponível ${num(avail)}.`}return ""}
window.salvarManejoV127=function(){estrutura();const id=$("manejoIdV127").value||novoId(),old=estado.manejos.find(x=>x.id===id),status=$("manejoStatusV127").value,talhaoId=$("manejoTalhaoV127").value,safraId=$("manejoSafraV127").value,prod=lerProdutos();if(!talhaoId){toast("Selecione o talhão.");return}if(!safraId){toast("Selecione a safra.");return}const safra=estado.safras.find(s=>s.id===safraId);if(safra?.fechada&&!old){toast("Não é possível criar manejo em safra fechada.");return}if(status==="concluido"){const err=validateStock(prod,id);if(err){toast(err);return}}const obj={...(old||{}),id,data:$("manejoDataV127").value||hoje(),status,talhaoId,safraId,tipo:$("manejoTipoV127").value,responsavel:$("manejoResponsavelV127").value.trim(),obs:$("manejoObsV127").value.trim(),produtos:prod,custoInsumos:0};estado.movimentacoesInsumos=estado.movimentacoesInsumos.filter(m=>m.manejoId!==id);if(status==="concluido"){for(const p of prod){const i=insumo(p.insumoId),cm=custoMedioInsumoV126(p.insumoId);obj.custoInsumos+=p.quantidade*cm;estado.movimentacoesInsumos.push({id:novoId(),insumoId:p.insumoId,tipo:"saida",data:obj.data,quantidade:p.quantidade,custoUnitario:cm,talhaoId,manejoId:id,obs:`Manejo: ${obj.tipo}`,criadoEm:new Date().toISOString()})}obj.concluidoEm=old?.concluidoEm||new Date().toISOString()}else obj.concluidoEm="";const ix=estado.manejos.findIndex(x=>x.id===id);if(ix>=0)estado.manejos[ix]=obj;else estado.manejos.push(obj);historicoV126(old?"Manejo atualizado":"Manejo cadastrado",`${obj.tipo} • ${nomeTalhao(talhaoId)}`,"manejo");fecharModal("modalManejoV127");persistir();toast(status==="concluido"?"Manejo concluído e estoque atualizado.":"Manejo programado.")};
window.concluirManejoV127=function(id){const m=estado.manejos.find(x=>x.id===id);if(!m)return;abrirManejoV127(id);setTimeout(()=>{$("manejoStatusV127").value="concluido";previewManejoV127()},50)};
window.excluirManejoV127=function(id){const m=estado.manejos.find(x=>x.id===id);if(!m)return;const msg=m.status==="concluido"?"Excluir este manejo? As saídas de insumos ligadas a ele serão estornadas do histórico de estoque.":"Excluir este manejo programado?";if(!confirm(msg))return;estado.movimentacoesInsumos=estado.movimentacoesInsumos.filter(x=>x.manejoId!==id);estado.manejos=estado.manejos.filter(x=>x.id!==id);historicoV126("Manejo excluído",`${m.tipo} • ${nomeTalhao(m.talhaoId)}`,"manejo");persistir()};
window.renderManejosV127=function(){estrutura();const fs=$("fManejoStatusV127")?.value||"todos",ft=$("fManejoTalhaoV127")?.value||"todos",fsa=$("fManejoSafraV127")?.value||"todos",q=($("fManejoBuscaV127")?.value||"").toLowerCase();let xs=estado.manejos.filter(m=>(fs==="todos"||m.status===fs)&&(ft==="todos"||m.talhaoId===ft)&&(fsa==="todos"||m.safraId===fsa)&&(!q||`${m.tipo} ${m.responsavel||""} ${m.obs||""} ${nomeTalhao(m.talhaoId)}`.toLowerCase().includes(q))).sort((a,b)=>(b.data||"").localeCompare(a.data||""));const safraAtiva=estado.safraAtivaId,prog=estado.manejos.filter(m=>m.status==="programado").length,conc=estado.manejos.filter(m=>m.status==="concluido"&&(!safraAtiva||m.safraId===safraAtiva)).length,custo=estado.manejos.filter(m=>m.status==="concluido"&&(!safraAtiva||m.safraId===safraAtiva)).reduce((s,m)=>s+custoManejo(m),0),lim=new Date();lim.setDate(lim.getDate()+7);const lims=lim.toISOString().slice(0,10),prox=estado.manejos.filter(m=>m.status==="programado"&&m.data>=hoje()&&m.data<=lims).length;if($("manejKpiProgramadosV127"))$("manejKpiProgramadosV127").textContent=prog;if($("manejKpiConcluidosV127"))$("manejKpiConcluidosV127").textContent=conc;if($("manejKpiCustoV127"))$("manejKpiCustoV127").textContent=moeda(custo);if($("manejKpiProximosV127"))$("manejKpiProximosV127").textContent=prox;if($("listaManejosV127"))$("listaManejosV127").innerHTML=xs.length?xs.map(m=>`<div class="v127-manejo-card ${manejoOverdue(m)?"overdue":""}"><div class="head"><div><h4>${esc(m.tipo)} • ${esc(nomeTalhao(m.talhaoId))}</h4><div class="meta">${dataBR(m.data)} • ${esc(safraNomeV124(m.safraId))}${m.responsavel?` • ${esc(m.responsavel)}`:""}${manejoOverdue(m)?" • ATRASADO":""}</div></div><span class="v127-status ${m.status}">${m.status==="concluido"?"CONCLUÍDO":"PROGRAMADO"}</span></div>${m.produtos?.length?`<div class="v127-product-chips">${produtosHTML(m.produtos)}</div>`:""}${m.obs?`<div class="section-note" style="margin-top:8px">${esc(m.obs)}</div>`:""}<div class="v127-manejo-foot"><div class="v127-manejo-cost"><small>Custo dos insumos aplicados</small><strong>${m.status==="concluido"?moeda(custoManejo(m)):"—"}</strong></div><div class="btnrow">${m.status==="programado"?`<button class="btn primary" onclick="concluirManejoV127('${m.id}')">Concluir</button>`:""}<button class="btn secondary" onclick="abrirManejoV127('${m.id}')">Editar</button><button class="btn danger" onclick="excluirManejoV127('${m.id}')">Excluir</button></div></div></div>`).join(""):`<div class="v124-empty">Nenhum manejo encontrado.</div>`};
function fillFilters(){if($("fManejoTalhaoV127")){const v=$("fManejoTalhaoV127").value;$("fManejoTalhaoV127").innerHTML=`<option value="todos">Todos os talhões</option>`+estado.talhoes.map(t=>`<option value="${t.id}">${esc(t.nome)}</option>`).join("");if([...$("fManejoTalhaoV127").options].some(o=>o.value===v))$("fManejoTalhaoV127").value=v}if($("fManejoSafraV127")){const v=$("fManejoSafraV127").value;$("fManejoSafraV127").innerHTML=`<option value="todos">Todas as safras</option>`+estado.safras.map(s=>`<option value="${s.id}">${esc(s.nome)}</option>`).join("");if([...$("fManejoSafraV127").options].some(o=>o.value===v))$("fManejoSafraV127").value=v}}

/* extend talhão ficha */
const baseFicha=window.renderFichaTalhaoV124;window.renderFichaTalhaoV124=function(){baseFicha();const id=$("fichaTalhaoIdV124")?.value,sf=$("fichaTalhaoSafraV124")?.value||"todos",c=custoTalhao(id,sf),box=$("fichaTalhaoMetricasV124");if(box&&!box.querySelector(".v127-cost-manejo-metric")){const prod=producaoSafraV124(sf,id);box.insertAdjacentHTML("beforeend",`<div class="v124-metric v127-cost-manejo-metric"><small>Insumos aplicados</small><strong>${moeda(c)}</strong><span>${prod>0?`${moeda(c/prod)} por saca produzida`:"Custo médio de estoque no momento da aplicação"}</span></div>`)}const solo=$("fichaTalhaoSoloV124");if(solo&&!solo.querySelector(".v127-cost-extra")){const ms=estado.manejos.filter(m=>m.talhaoId===id&&m.status==="concluido"&&(sf==="todos"||m.safraId===sf)).length;solo.insertAdjacentHTML("beforeend",`<div class="v127-cost-extra"><small>Manejos concluídos no período</small><strong>${ms} • ${moeda(c)} em insumos aplicados</strong></div>`)}};

/* dashboard attention */
const baseAttention=window.renderPainelAtencaoV121;window.renderPainelAtencaoV121=function(){baseAttention();const el=$("painelAtencaoV121");if(!el)return;const atras=estado.manejos.filter(m=>manejoOverdue(m)),lim=new Date();lim.setDate(lim.getDate()+7);const ls=lim.toISOString().slice(0,10),prox=estado.manejos.filter(m=>m.status==="programado"&&m.data>=hoje()&&m.data<=ls);if(atras.length)el.insertAdjacentHTML("afterbegin",`<button class="v121-attention-card danger" onclick="trocarAba('talhoes',document.querySelector('[data-nav=perfil]'));setTimeout(()=>document.querySelector('.v127-manejo-head')?.scrollIntoView({behavior:'smooth'}),100)"><strong>${atras.length} manejo(s) atrasado(s)</strong><span>Revise atividades programadas que já passaram da data.</span></button>`);else if(prox.length)el.insertAdjacentHTML("beforeend",`<button class="v121-attention-card" onclick="trocarAba('talhoes',document.querySelector('[data-nav=perfil]'));setTimeout(()=>document.querySelector('.v127-manejo-head')?.scrollIntoView({behavior:'smooth'}),100)"><strong>${prox.length} manejo(s) nos próximos 7 dias</strong><span>Planejamento da lavoura.</span></button>`)};

/* sync details */
window.abrirSyncV127=function(){estrutura();const p=Number(window.__pendenciasSyncV127||0),last=estado.syncInfoV127?.localUpdatedAt;$("syncDetalheV127").innerHTML=`<strong>Sincronização V12.7</strong><div class="v127-sync-grid"><div><small>Alterações pendentes</small><strong>${p}</strong></div><div><small>Dispositivo</small><strong>${deviceId.slice(0,8)}</strong></div><div><small>Última alteração local</small><strong>${last?new Date(last).toLocaleString("pt-BR"):"—"}</strong></div><div><small>Modo</small><strong>Mesclagem por registro</strong></div></div><p style="margin-top:9px">Quando dois aparelhos alteram registros diferentes, o app mescla os dados antes de gravar. Se estiver sem internet, as alterações permanecem salvas neste aparelho e são enviadas quando a conexão voltar.</p>`;abrirModal("modalSyncV127")};window.sincronizarAgoraV127=function(){if(window.cloudSync?.enviarAgora){window.cloudSync.enviarAgora().then(()=>{toast("Sincronização solicitada.");abrirSyncV127()}).catch(()=>toast("Não foi possível sincronizar agora."))}};

/* search and favorites */
if(window.FAVORITOS_V126===undefined){/* const in older scope is not exported */}
const oldIndex=window.indiceBuscaV126; // usually lexical, inaccessible
const baseBusca=window.renderBuscaGlobalV126;window.renderBuscaGlobalV126=function(){baseBusca();const q=($("buscaGlobalV126")?.value||"").trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(!q)return;const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const extra=estado.manejos.filter(m=>norm(`${m.tipo} ${m.responsavel||""} ${m.obs||""} ${nomeTalhao(m.talhaoId)}`).includes(q)).slice(0,15);if(extra.length){const box=$("buscaGlobalResultadosV126");box.insertAdjacentHTML("beforeend",extra.map(m=>`<button class="v126-search-item" onclick="fecharModal('modalBuscaGlobalV126');trocarAba('talhoes',document.querySelector('[data-nav=perfil]'));setTimeout(()=>abrirManejoV127('${m.id}'),80)"><span class="ic">🌱</span><span class="main"><strong>${esc(m.tipo)} • ${esc(nomeTalhao(m.talhaoId))}</strong><small>${dataBR(m.data)} • ${m.status}</small></span><span class="type">Manejo</span></button>`).join(""))}};

/* PDF maneios extension */
const basePDF=window.gerarPDFV126;window.gerarPDFV126=function(){if($("pdfTipoV126")?.value!=="manejos")return basePDF();if(!window.jspdf?.jsPDF){toast("Biblioteca de PDF ainda não carregou.");return}const {jsPDF}=window.jspdf,doc=new jsPDF({unit:"mm",format:"a4"}),sf=$("pdfSafraV126").value;let y=pdfCabV126(doc,`Manejo da lavoura • ${sf==="todos"?"Todas as safras":safraNomeV124(sf)}`);const xs=estado.manejos.filter(m=>sf==="todos"||m.safraId===sf).slice().sort((a,b)=>(b.data||"").localeCompare(a.data||""));y=pdfTabelaTextoV126(doc,y,xs.map(m=>`${dataBR(m.data)} • ${nomeTalhao(m.talhaoId)} • ${m.tipo} • ${m.status} • insumos ${moeda(custoManejo(m))}${m.responsavel?` • ${m.responsavel}`:""}`));doc.save(`financeiro-sitio-manejos-${hoje()}.pdf`);fecharModal("modalRelatorioPDFV126")};

/* set/get state final */
window.appBridge.setEstado=function(n){suspendSync=true;let gerados=0;try{estado={lancamentos:Array.isArray(n?.lancamentos)?n.lancamentos:[],talhoes:Array.isArray(n?.talhoes)?n.talhoes:[],colheitas:Array.isArray(n?.colheitas)?n.colheitas:[],vendas:Array.isArray(n?.vendas)?n.vendas:[],trabalhadores:Array.isArray(n?.trabalhadores)?n.trabalhadores:[],apanhas:Array.isArray(n?.apanhas)?n.apanhas:[],lotes:Array.isArray(n?.lotes)?n.lotes:[],safras:Array.isArray(n?.safras)?n.safras:[],safraAtivaId:n?.safraAtivaId||"",categorias:n?.categorias&&typeof n.categorias==="object"?n.categorias:{receita:[],despesa:[]},pessoas:Array.isArray(n?.pessoas)?n.pessoas:[],cotacaoCafe:n?.cotacaoCafe&&typeof n.cotacaoCafe==="object"?n.cotacaoCafe:{},analisesSolo:Array.isArray(n?.analisesSolo)?n.analisesSolo:[],baixasFinanceiras:Array.isArray(n?.baixasFinanceiras)?n.baixasFinanceiras:[],contasFinanceiras:Array.isArray(n?.contasFinanceiras)?n.contasFinanceiras:[],recorrenciasFinanceiras:Array.isArray(n?.recorrenciasFinanceiras)?n.recorrenciasFinanceiras:[],orcamentosSafra:Array.isArray(n?.orcamentosSafra)?n.orcamentosSafra:[],fechamentosSafra:Array.isArray(n?.fechamentosSafra)?n.fechamentosSafra:[],insumos:Array.isArray(n?.insumos)?n.insumos:[],movimentacoesInsumos:Array.isArray(n?.movimentacoesInsumos)?n.movimentacoesInsumos:[],lixeiraV126:Array.isArray(n?.lixeiraV126)?n.lixeiraV126:[],historicoV126:Array.isArray(n?.historicoV126)?n.historicoV126:[],favoritosV126:Array.isArray(n?.favoritosV126)?n.favoritosV126:[],manejos:Array.isArray(n?.manejos)?n.manejos:[],syncDeletedV127:n?.syncDeletedV127&&typeof n.syncDeletedV127==="object"?n.syncDeletedV127:{},syncInfoV127:n?.syncInfoV127&&typeof n.syncInfoV127==="object"?n.syncInfoV127:{}};estrutura();migrarLotesAntigos();gerados=gerarRecorrenciasAteV122(fimHorizonteV122(60));salvarLocal();window.__snapshotV127=structuredClone(estado);renderTudo();iniciarAtualizacaoCotacao()}finally{suspendSync=false}if(gerados>0)setTimeout(()=>{salvarLocal();if(window.cloudSync)window.cloudSync.agendar()},100)};
window.appBridge.getEstado=function(){estrutura();return structuredClone(estado)};
const baseClear=window.appBridge.limparUsuario;window.appBridge.limparUsuario=function(){usuarioAtual=null;estado={lancamentos:[],talhoes:[],colheitas:[],vendas:[],trabalhadores:[],apanhas:[],lotes:[],safras:[],safraAtivaId:"",categorias:{receita:[],despesa:[]},pessoas:[],cotacaoCafe:{},analisesSolo:[],baixasFinanceiras:[],contasFinanceiras:[],recorrenciasFinanceiras:[],orcamentosSafra:[],fechamentosSafra:[],insumos:[],movimentacoesInsumos:[],lixeiraV126:[],historicoV126:[],favoritosV126:[],manejos:[],syncDeletedV127:{},syncInfoV127:{}};estrutura();window.__snapshotV127=structuredClone(estado);$("authScreen").classList.remove("hidden");renderTudo()};
const baseTudo=window.renderTudo;window.renderTudo=function(){estrutura();baseTudo();fillFilters();renderManejosV127()};
const basePerfil=window.renderPerfil;window.renderPerfil=function(){estrutura();basePerfil()};
window.baixarBackup=function(){estrutura();const payload={versao:"12.10",exportadoEm:new Date().toISOString(),estado};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`backup-financeiro-sitio-v12-10-${hoje()}.json`;a.click();URL.revokeObjectURL(a.href)};

document.addEventListener("DOMContentLoaded",()=>setTimeout(()=>{estrutura();window.__snapshotV127=structuredClone(estado);fillFilters();renderManejosV127()},450));
})();
